apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: ckaquest
  labels:
    app: web
spec:
  containers:
    - name: web
      image: nginx:1.25
      ports:
        - containerPort: 80
      readinessProbe:
        httpGet:
          path: /
          port: 8080        # BUG: nginx listens on 80, not 8080
        initialDelaySeconds: 3
        periodSeconds: 5
