apiVersion: v1
kind: Pod
metadata:
  name: cache
  namespace: ckaquest
  labels:
    app: cache
spec:
  nodeSelector:
    disktype: ssd
  containers:
    - name: cache
      image: redis:7
      resources:
        requests:
          cpu: "100m"
          memory: "64Mi"
