apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: ckaquest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: nginx:1.99.99-alpine   # BUG: this tag does not exist
          ports:
            - containerPort: 80
