apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: ckaquest
  labels:
    app: web
spec:
  containers:
    - name: web
      image: nginx:1.25
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /              # nginx serves index.html at /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
        failureThreshold: 3
