apiVersion: v1
kind: Pod
metadata:
  name: worker
  namespace: ckaquest
  labels:
    app: worker
spec:
  volumes:
    - name: shared-vol
      emptyDir: {}
  initContainers:
    - name: init-config
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          echo '{"level":"INFO","workers":4}' > /work/config.json
          echo "Config written to /work/config.json"
      volumeMounts:
        - name: shared-vol
          mountPath: /work      # init writes here
  containers:
    - name: main
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          echo "Reading config..."
          cat /data/config.json && echo "Config OK!" && sleep 3600
      volumeMounts:
        - name: shared-vol
          mountPath: /data      # BUG: should be /work to share with init container
