apiVersion: v1
kind: Pod
metadata:
  name: compute
  namespace: ckaquest
  labels:
    app: compute
spec:
  containers:
    - name: compute
      image: nginx:1.25
      resources:
        requests:
          cpu: "100"
          memory: "200Gi"
