apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: ckaquest
spec:
  replicas: 3
  strategy:
    type: RollingUpdate       # fixed
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: nginx:1.25
          ports:
            - containerPort: 80
