apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitor-sa-pod-reader
  namespace: ckaquest
subjects:
  - kind: ServiceAccount
    name: monitor-sa
    namespace: ckaquest
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
