apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: ckaquest
  labels:
    app: web
spec:
  containers:
    - name: web
      image: nginx:1.25
      resources:
        requests:
          memory: "1Mi"
        limits:
          memory: "2Mi"
